### ISSUE TITLE
Cannot start after npm start

### ISSUE THREAD

**Issue by rafaelanastacioalves** [DangLienMinh/webrtc_server#1]
Hi,
can anyone help me to start de server side? The port isn't working. I believe I've installed everything....
![image](https://cloud.githubusercontent.com/assets/5789073/16399514/7c47c756-3ca9-11e6-9b35-fa3befe8ade0.png)
![image](https://cloud.githubusercontent.com/assets/5789073/16399521/952b1598-3ca9-11e6-9cf0-955eb642b6e9.png)

**Comment by minhdl93** [comment]
Hi @rafaelanastacioalves, you have stopped the nodejs server because you press Command+c. If you want to do another command please open another terminal. That would be fine!

**Comment by rafaelanastacioalves** [comment]
@DangLienMinh , 
I stopped it because it was taking too long...
That's why I started this thread...
Do you need me to do anything to help debugging the backend? I'm not good with this stack.
Regards,

**Comment by rafaelanastacioalves** [comment]
I've just forgot starting mongodb as explained in their site.
So sorry... If you want, you can delete this stupid thread. :)
