### ISSUE TITLE
I can register just one user

### ISSUE THREAD

**Issue by leo-dias** [DangLienMinh/webrtc_server#2]
Hi! I'm trying to test your webrtc-server, it work fine with one user, when I try to register other one from the webrtc-client, I got an erro saying: "Cannot register, please try again!".

The funny is the first time that I tried, was success, this error just occur at the second time.

Can you help me?

Thanks.

**Comment by Longstreet** [comment]
It's because the passwords have to be unique per user as well as the username. It's something I noticed a few days ago as well.
