### ISSUE TITLE
conection refused

### ISSUE THREAD

**Issue by dreaminglwj** [DangLienMinh/webrtc_server#3]
I have installed mongodb, but when request the url "***:3000/register" it response with status = -1.

**Comment by rafaelanastacioalves** [comment]
I've just started this project from zero and I'm having the same issue.

**Comment by rafaelanastacioalves** [comment]
I've just remembered the solution: use YOUR ip. It is not 127.0.0.1.
I hope this can help. Just check if you're doing this part correctly.
Regards,

**Comment by minhdl93** [comment]
Problem solved, close the issue now. Thank you
