### ISSUE TITLE
How to update a user password

### ISSUE THREAD

**Issue by alexruskovski** [DangLienMinh/webrtc_server#4]
Its not a error associated with the application. I want to add functionality to change the user password. Since i'm a biginer with Node I will appreciate your help. This is what I have already done.
routes.js

var update(req,res){

};
app.post('/update',update);
Im not even sure if this is correct way to catch update from url.

**Comment by minhdl93** [comment]
Please check some example functions here, for demo how to communicate with the user model.
https://github.com/DangLienMinh/webrtc_server/blob/master/app/routes.js

https://github.com/DangLienMinh/webrtc_server/blob/master/app/socketHandler.js

**Comment by alexruskovski** [comment]
@DangLienMinh  Thank you for your reply. Will check now.

**Comment by alexruskovski** [comment]
@DangLienMinh  I can figure it out how to update user password field.


var register = function(req, res) {

}

**Comment by alexruskovski** [comment]
@DangLienMinh  I can figure it out how I can update user password filed.
let say I will add listener for example: 
POST: http://127.0.0.1:3000/update will pass here user id for which I will need to change the password.

I will append app/routes.js with

app.post('/update',update); // to listen for /update and will call update fun

and here is the update function
var update = function(req,res){
  // here I will need to find that user with that specific ID and update his password
}
Is it correct approach? Please let me know how to update the password files for specific user .
Thank you so much

**Comment by minhdl93** [comment]
Yes, you are on the right track. 
As you can see here the username along with the password. As the username is unique, you can select the user then update the password on that user. You can see the **compare password** function at the end of the user.js file.
https://github.com/DangLienMinh/webrtc_server/blob/master/app/model/user.js

You can create the same function and check in this file to see how to user the  **compare password** function

https://github.com/DangLienMinh/webrtc_server/blob/master/app/routes.js

**Comment by minhdl93** [comment]
If no more comment, then I will close the issue. Thank you
